version: "3.8"

services:
  redis:
    image: redis:7-alpine
    container_name: scanner-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  api:
    build: .
    container_name: scanner-api
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=redis://redis:6379/0
      - UPLOAD_DIR=/tmp/security_scans
      - REPORT_DIR=/app/reports
      - TRIVY_TEMPLATE=/app/trivy-html.tpl
      # هنا خليه يقرأ من الـ .env أوتوماتيك
      - DEFECTDOJO_URL=${DEFECTDOJO_URL}
      - DEFECTDOJO_API_KEY=${DEFECTDOJO_TOKEN}
    volumes:
      - reports_data:/app/reports
    depends_on:
      - redis
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --workers 4

  worker:
    build: .
    container_name: scanner-worker
    restart: unless-stopped
    environment:
      - REDIS_URL=redis://redis:6379/0
      - UPLOAD_DIR=/tmp/security_scans
      - REPORT_DIR=/app/reports
      - TRIVY_TEMPLATE=/app/trivy-html.tpl
      # هنا خليه يقرأ من الـ .env أوتوماتيك
      - DEFECTDOJO_URL=${DEFECTDOJO_URL}
      - DEFECTDOJO_API_KEY=${DEFECTDOJO_TOKEN}
    volumes:
      - reports_data:/app/reports
    depends_on:
      - redis
    command: celery -A celery_app worker --loglevel=info --concurrency=2

volumes:
  redis_data:
  reports_data:
